### ISSUE TITLE
How do I set it in my taskbar so that it's there at every computer startup?

### ISSUE THREAD

**Issue by arthur19705** [myfix16/BatteryTracker#2]
Hi,
Thank you for BatteryTrackerFramework v.1.0 , it's very well done and useful.
I have a question:
How do I set it so that it appears automatically every time I start my computer, in my Taskbar, next to the Battery Icon?
Could you provide some instructions/explanation on how to achieve this?
Thank you very much,
Arthur from Italy

**Comment by myfix16** [comment]
Hello,
This [MS article](https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd) provides the guidance. 
Moreover, I would consider adding this feature to BatteryTracker to make such process easier.

**Comment by myfix16** [comment]
update: release v1.1 adds this functionality.

**Comment by myfix16** [comment]
Closed for lacking further response.
