### ISSUE TITLE
当电量充满的时候，希望字母F可以出现在正中间

### ISSUE THREAD

**Issue by iKineticate** [myfix16/BatteryTracker#25]
微软商店中的版本：1.4.0.0
windows11 on arm：22H2，23403.1001
希望作者满足一下小小的强迫症(∩_∩)。
感谢你的应用，祝你生活愉快，身体健康。

**Comment by myfix16** [comment]
这个和引用的任务栏图标库 H.NotifyIcon 有关，我之前尝试了一下居中没成功，后续更新尽量😂

**Comment by myfix16** [comment]
@iKineticate 该问题会在 #30 修复。下个版本更新会包含这个补丁。

**Comment by iKineticate** [comment]
> @iKineticate 该问题会在 #30 修复。下个版本更新会包含这个补丁。

给你点个大赞
