### ISSUE TITLE
I hope to add an option that can turn the battery percentage into a direct display of battery available time.

### ISSUE THREAD

**Issue by Mariomoprc** [myfix16/BatteryTracker#60]
this is a good idea.

**Comment by myfix16** [comment]
Do you mean showing the available time directly in the taskbar?

As far as I know, there are limitations on the max width of the taskbar icons of third-party Windows apps. And I believe the available time will be truncated :(. 

However, I think https://github.com/myfix16/BatteryTracker/issues/50#issuecomment-1631830871 is a good alternative solution.
