### ISSUE TITLE
Some advices

### ISSUE THREAD

**Issue by wlisboy** [myfix16/BatteryTracker#64]
1. Hope to add a transparent taskbar to solve the digital blur problem
2. I hope that the battery number can be changed to different colors; for example, the color can be changed under different values. Of course, I would like it very much if it supports user-defined colors.
3. I like this project very much. It solves my daily problem of not knowing how much battery is left. At the same time, I hope you can keep the UI of your product, which looks very simple. I hope you can adopt these suggestions of mine ~ I hope your work goes well, thank you

**Comment by myfix16** [comment]
Hi, thanks for your feedback! I have a couple of questions:

1. Can you describe the "digital blur problem" in detail and elaborate on the meaning of "a transparent taskbar"? I don't quite understand this point 😅
2. Are you suggesting that, for example, the color becomes yellow when % < 60% and becomes red when % < 20% ?

**Comment by wlisboy** [comment]
Numbers in taskbar are blurred: With the help of three-party software, the taskbar is transparent, and the numbers are blurred and unclear. In addition, the second item you mentioned is what I want to achieve.

**Comment by myfix16** [comment]
> Numbers in taskbar are blurred: With the help of three-party software, the taskbar is transparent, and the numbers are blurred and unclear. In addition, the second item you mentioned is what I want to achieve.

I get it. Are you using translucent  TB or any other software? Can you provide the same so that I can try it?

For the second feature. I'm not sure whether this will fit with native Windows 11 components. I may do some experiments first.

**Comment by wlisboy** [comment]
Sorry. Due to work reasons can not promptly reply to your message!
else. my computer uses translucent TB，I don't know if it's my screen resolution or if your software font looks a little fuzzy at the edges in a transparent state

**Comment by myfix16** [comment]
Ok, I will investigate the issue. Thanks!
