### ISSUE TITLE
Luri Bakhtiari's language is not displayed in the program's language settings

### ISSUE THREAD

**Issue by hosseinabaspanah** [myfix16/BatteryTracker#68]
**Describe the bug**

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Application language'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version [e.g. Windows 11 22H2 version 22623.1095]

**Additional context**

**Comment by myfix16** [comment]
It seems like Luri Bakhtiari is not on Microsoft's language list manifest. I will try to find other ways to add this language to the app. Thanks for the issue.

**Comment by myfix16** [comment]
According to https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/supported-languages?pivots=store-installer-msix, I am not able to add Luri Bakhtiari to a store app :( 

I apologize for that. And I will add the language once Microsoft supports it. Thanks for the translation!
