### ISSUE TITLE
Please make sure that the battery readings are visible on the taskbar or in the system tray next to the battery icon!

### ISSUE THREAD

**Issue by 6adp** [myfix16/BatteryTracker#70]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 6adp** [comment]
Please make sure that the battery readings are visible on the taskbar or in the system tray next to the battery icon!

**Comment by myfix16** [comment]
Are you using Windows 11 or Windows 10? I don't believe this is doable in Win 11 :(
