### ISSUE TITLE
App freezes, wrong battery percentage shown

### ISSUE THREAD

**Issue by ericswpark** [myfix16/BatteryTracker#73]
**Describe the bug**
The app sometimes shows the wrong battery percentage, freezing on a certain value. The app is still responsive (responds to right-click and the context menu shows up) but the battery value continues to be wrong.

**To Reproduce**
Unknown reproduction steps

**Expected behavior**
The value should continuously update.

**Screenshots**
![image](https://github.com/user-attachments/assets/3a449da1-c385-4c0b-bcb6-b33786b00d5e)

**Desktop (please complete the following information):**
 - OS Version 
Windows 11 23H2 (OS Build 22631.4037)

**Additional context**

**Comment by myfix16** [comment]
Can you upload the log so I can investigate the issue? The logs can be found using settings/open log folders? Thanks!

**Comment by ericswpark** [comment]
@myfix16 sorry, but I uninstalled the app. Feel free to close the issue, or maybe someone else will have the same problem and post logs.
